#!/usr/bin/env bash

#/ command: fedorchuk:ivan: "displays all variables"
#/ usage: rerun fedorchuk:ivan [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: 

. "$RERUN_MODULE_DIR/lib/functions.sh" "ivan" || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

awk -F'=' '{ print "\33[31m"$1" \33[32m"$2 }' <<< "$(env)"

# Done. Exit with last command exit status.
exit $?

